### PR TITLE
Add support for MS SQL Server

### PR DESCRIPTION
**Pull request by jakub-klapka**

### CODE REVIEW

**Comment by jakub-klapka** [comment]
Hello, do you have an idea, what that means: https://insight.sensiolabs.com/projects/b38ed189-9b84-455f-90ad-d8388d243274/analyses/88?status=violations#505177370?

**Comment by freekmurze** [comment]
I'll fix that insights issue myself, don't bother with it 😄 

I'd don't like that script file. Could you do everything regarding the dropping of constraints in the class itself?

**Comment by jakub-klapka** [comment]
Well, I didn't find easy one-line way, how to drop all the constraints in mssql. I can, of course, put the contents of the sql script into class as string, but the script thing seems more clean to me. But if you are OK with that, I can do it. How do you feel about heredocs? :)

**Comment by freekmurze** [comment]
Please try to use a normal string. Not a fan of heredocs 😄

**Comment by jakub-klapka** [comment]
I think it's ready now.

**Comment by freekmurze** [comment]
Thanks!

**Pull request merged**
